### ISSUE TITLE
Not an issue, just a question please

### ISSUE THREAD

**Issue by JenieX** [4ndrs/PureMPV#3]
I would like to know how you learned about drawing shapes on the video, like that selecting box.

It seems like your script is the only script that has an example in JavaScript, which is the language I know, on how to do that, and I can't figure everything about it. Like I'm trying to draw a rectangle shaped bar that indicates the playtime in JavaScript, only I don't know the API to achieve that and I can't find anything about it online.

Could you please lead me somewhere to learn more about that, thank you.

**Comment by 4ndrs** [comment]
I'm using the [ASS File Format Specification](http://www.tcax.org/docs/ass-specs.htm) with [mp.create_osd_overlay("ass-events")](https://mpv.io/manual/master/#lua-scripting-mp-create-osd-overlay(format)). There is a drawing mode with `\p1` and `\p0` tags, which you can use to draw shapes with drawing commands. Here are the commands (quoted from the linked document):

> Drawing commands:
> m \<x\> \<y\>                 Moves the cursor to \<x\>, \<y\>
> n \<x\> \<y\>                  Moves the cursor to \<x\>, \<y\> (unclosed shapes will be left open)
> l \<x\> \<y\>                   Draws a line to \<x\>, \<y\>
> b \<x1\> \<y1\> \<x2\> \<y2\> \<x3\> \<y3\> 3rd degree bezier curve to point 3 using point 1 and 2 as the control points
> s \<x1\> \<y1\> \<x2\> \<y2\> \<x3\> \<y3\> .. \<xN\> \<yN\> 3rd degree uniform b-spline to point N, must contain at least 3 coordinates
> p \<x\> \<y\>                  extend b-spline to \<x\>, \<y\>
> c                                close b-spline
>
> Things you should know:
>     - Commands must appear after {\p1+} and before {\p0}.         (except for \clip(..))
>      - Drawings must always start with a move to command.
>      - Drawings must form a closed shape.
>     -  All unclosed shape will be closed with a straight line automatically.
>     - Overlapping shapes in the Dialogue line will be XOR-ed with each-other.
>      - If the same command follows another, it isn’t needed to write its identifier letter again, only the coordinates.
>      - The coordinates are relative to the current cursor position (baseline) and the alignment mode.
>      - Commands p and c should only follow other b-spline commands.
> 
> Examples:
>      Square: m 0 0 l 100 0 100 100 0 100
>      Rounded square: m 0 0 s 100 0 100 100 0 100 c (c equals to “p 0 0 100 0 100 100” in this case)
>      Circle (almost): m 50 0 b 100 0 100 100 50 100 b 0 100 0 0 50 0 (note that the 2nd ‘b’ is optional here)

[Here ](https://github.com/4ndrs/PureMPV/blob/main/src/cropbox.ts#L143) I'm moving the cursor (m) to the starting position `x,y` then drawing line 1 `(x = x + width, y = y)`, line2 `(x = x + width, y = y + height)`, line3 `(x = x, y = y + height)`, the 4th line is not needed since it auto closes with a straight line.  
```typescript
  const _box =
    `{\\p1}m ${x} ${y} l ${x + w} ${y} ${x + w} ` +
    `${y + h} ${x} ${y + h} {\\p0}`;
```

**Comment by JenieX** [comment]
Super awesome. 

Thank you very much. 😄
